import 'package:ants_companion/domain/ant_skills/models/ant_skill.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension AntSkillTitleExtension on AntSkill {
  String skillTitle(AppLocalizations l10n) => switch (this) {
        AntSkillNotImplemented() => 'Name Unknown',
        DominanceThree() => l10n.dominance3SkillTitle,
        TertiaryDefense() => l10n.tertiaryDefenseSkillTitle,
        TertiaryAttack() => l10n.tertiaryAttackSkillTitle,
        AntSkillSeven() => l10n.antSkillSevenTitle(l10n),
        AcidGeneralWeaknessRaidSkill() =>
          l10n.acidGeneralWeaknessRaidSkillTitle,
        AcidGeneralHyperAttackSkill() => l10n.acidGeneralHyperAttackSkillTitle,
        AcidGeneralDeadlyStrikeSkill() =>
          l10n.acidGeneralDeadlyStrikeSkillTitle,
        GoldenCrystalBattleFeverSkill() =>
          l10n.goldenCrystalBattleFeverSkillTitle,
        ColonyLeaderSkill() => l10n.colonyLeaderSkillTitle,
        GoldenCrystalViolentlyPoisonousSkill() =>
          l10n.goldenCrystalViolentlyPoisonousSkillTitle,
        GoldenCrystalMasterHunterSkill() =>
          l10n.goldenCrystalMasterHunterSkillTitle,
        GoldenCrystalSwoopSkill() => l10n.goldenCrystalSwoopSkillTitle,
        AntSkillSevenMarchSpeed() => throw UnimplementedError(),
        AttaSexdensDefensiveOffenceSkill() =>
          l10n.attaSexdensDefensiveOffenceSkillTitle,
        AttaSexdensJawRaidSkill() => l10n.attaSexdensJawRaidSkillTitle,
        AttaSexdensThornAssaultSkill() =>
          l10n.attaSexdensThornAssaultSkillTitle,
        BansheePandaVelvetShieldSkill() =>
          l10n.bansheePandaVelvetShieldSkillTitle,
        BansheePandaAllureAttackSkill() =>
          l10n.bansheePandaAllureAttackSkillTitle,
        BansheePandaWarfareLeadershipSkill() =>
          l10n.bansheePandaWarfareLeadershipSkillTitle,
        BansheeVelvetSuperToxinSkill() => throw UnimplementedError(),
        BansheeVelvetVividColorSkill() => throw UnimplementedError(),
        BansheeVelvetWarfareLeadershipSkill() => throw UnimplementedError(),
        BlackCancerFluidLeachSkill() => throw UnimplementedError(),
        BlackCancerAdamantArmorSkill() => throw UnimplementedError(),
        BlackCancerWarfareLeadershipSkill() => throw UnimplementedError(),
        BlackKnightVengefulCounterattackSkill() => throw UnimplementedError(),
        BlackKnightBlackArmorMarsSkill() => throw UnimplementedError(),
        BlackKnightDarkSpikeAssaultSkill() => throw UnimplementedError(),
        BloodGiantSupportTeammatesSkill() => throw UnimplementedError(),
        BloodGiantImproveLineupSkill() => throw UnimplementedError(),
        BloodGiantKillingStrikeSkill() => throw UnimplementedError(),
        BrownRogueSurpriseStrikeSkill() => throw UnimplementedError(),
        BrownRogueCheapShotSkill() => throw UnimplementedError(),
        BrownRogueFindWeaknessSkill() => throw UnimplementedError(),
        BulletAntRampantAttackSkill() => throw UnimplementedError(),
        BulletAntBlitzkriegSkill() => throw UnimplementedError(),
        BulletAntSuppressingAttackSkill() => throw UnimplementedError(),
        CarpenterAntSteadyPaceSkill() => throw UnimplementedError(),
        CarpenterAntDistendedBellySkill() => throw UnimplementedError(),
        CarpenterAntPowerfulGazeSkill() => throw UnimplementedError(),
        CrematogasterInflataWinningStrategySkill() =>
          throw UnimplementedError(),
        CrematogasterInflataMasterMimicSkill() => throw UnimplementedError(),
        CrematogasterInflataHealingMucusSkill() => throw UnimplementedError(),
        CrimsonFraggerPiercingAttackSkill() => throw UnimplementedError(),
        CrimsonFraggerDoubleHitSkill() => throw UnimplementedError(),
        CrimsonFraggerAdequatePreparationSkill() => throw UnimplementedError(),
        CrimsonPearlBrutalCombosSkill() => throw UnimplementedError(),
        CrimsonPearlParasiticStingerSkill() => throw UnimplementedError(),
        CrimsonPearlVariableMimicsSkill() => throw UnimplementedError(),
        CyphomyrmexRimosusPowerfulHeadbuttSkill() => throw UnimplementedError(),
        CyphomyrmexRimosusGermPropagationSkill() => throw UnimplementedError(),
        CyphomyrmexRimosusBeneficialBacteriaSkill() =>
          throw UnimplementedError(),
        DarkGiantCounterStrikeSkill() => throw UnimplementedError(),
        DarkGiantMenaceSkill() => throw UnimplementedError(),
        DarkGiantWarfareLeadershipSkill() => throw UnimplementedError(),
        DarkHerculesFatalBiteSkill() => throw UnimplementedError(),
        DarkHerculesStrongGuardSkill() => throw UnimplementedError(),
        DarkHerculesBurningCourageSkill() => throw UnimplementedError(),
        DolichoderusBispinosusImmediateSupportSkill() =>
          throw UnimplementedError(),
        DolichoderusBispinosusAgileAttackSkill() => throw UnimplementedError(),
        DolichoderusBispinosusExtraDamageSkill() => throw UnimplementedError(),
        DriverAntBlitzkriegSkill() => throw UnimplementedError(),
        DriverAntSharpTearingSkill() => throw UnimplementedError(),
        DriverAntWeaknessStrikeSkill() => throw UnimplementedError(),
        DuskyLurkerSneakAttackSkill() => throw UnimplementedError(),
        DuskyLurkerApplyingTacticsSkill() => throw UnimplementedError(),
        DuskyLurkerTrueLeaderSkill() => throw UnimplementedError(),
        EmeraldJewelAntStealthAssassinateSkill() => throw UnimplementedError(),
        EmeraldJewelAntCruelParasitismSkill() => throw UnimplementedError(),
        EmeraldJewelAntParasiticDevourSkill() => throw UnimplementedError(),
        EnigmaticTaylorSneakAttackSkill() => throw UnimplementedError(),
        EnigmaticTaylorFootRendSkill() => throw UnimplementedError(),
        EnigmaticTaylorWarfareLeadershipSkill() => throw UnimplementedError(),
        FormicaClaraSleekChitinSkill() => throw UnimplementedError(),
        FormicaClaraAgileDashSkill() => throw UnimplementedError(),
        FormicaClaraDazzlingSwashSkill() => throw UnimplementedError(),
        GhostAntClearHeadSkill() => throw UnimplementedError(),
        GhostAntGhostStrikeSkill() => throw UnimplementedError(),
        GhostAntDeliberateAttackSkill() => throw UnimplementedError(),
        GiantToothWeaknessStrikeSkill() => throw UnimplementedError(),
        GiantToothDisablingAttackSkill() => throw UnimplementedError(),
        GiantToothBigBiteSkill() => throw UnimplementedError(),
        GoldArmorBigBiteSkill() => throw UnimplementedError(),
        GoldArmorRampantAttackSkill() => throw UnimplementedError(),
        GoldArmorBlitzkriegSkill() => throw UnimplementedError(),
        GoldenSpinyBigBiteSkill() => throw UnimplementedError(),
        GoldenSpinyPiercingAttackSkill() => throw UnimplementedError(),
        GoldenSpinyAmbushSkill() => throw UnimplementedError(),
        GoldenSugarBigBiteSkill() => throw UnimplementedError(),
        GoldenSugarPiercingStrikeSkill() => throw UnimplementedError(),
        GoldenSugarComboStrikesSkill() => throw UnimplementedError(),
        GoldenVenomRampantAttackSkill() => throw UnimplementedError(),
        GoldenVenomParalysisToxinSkill() => throw UnimplementedError(),
        GoldenVenomBladePincerSkill() => throw UnimplementedError(),
        GracefulTwigAntAcidicSpraySkill() => throw UnimplementedError(),
        GracefulTwigAntHuntingInstinctSkill() => throw UnimplementedError(),
        GracefulTwigAntUnyieldingDeterminationSkill() =>
          throw UnimplementedError(),
        GraveDiggerToxicSpraySkill() => throw UnimplementedError(),
        GraveDiggerNervePoisonSkill() => throw UnimplementedError(),
        GraveDiggerWarfareLeadershipSkill() => throw UnimplementedError(),
        GuardGeneralLightningBlitzkriegSkill() => throw UnimplementedError(),
        GuardGeneralAgileMovementSkill() => throw UnimplementedError(),
        GuardGeneralDisablingCombosSkill() => throw UnimplementedError(),
        HairyPantherRampageStrikeSkill() => throw UnimplementedError(),
        HairyPantherFurySwipeSkill() => throw UnimplementedError(),
        HairyPantherFierceNatureSkill() => throw UnimplementedError(),
        JackJumperRampantAttackSkill() => throw UnimplementedError(),
        JackJumperJumpingAttackSkill() => throw UnimplementedError(),
        JackJumperBlitzkriegSkill() => throw UnimplementedError(),
        JetBlackCounterAttackSkill() => throw UnimplementedError(),
        JetBlackSelfAdjustingSkill() => throw UnimplementedError(),
        JetBlackCarvedSkinSkill() => throw UnimplementedError(),
        LathySnifferDoublePowerSkill() => throw UnimplementedError(),
        LathySnifferTailAssaultSkill() => throw UnimplementedError(),
        LathySnifferFrequentlyStrengthenSkill() => throw UnimplementedError(),
        LeafDevourerKillingDoubleHitSkill() => throw UnimplementedError(),
        LeafDevourerBurningCourageSkill() => throw UnimplementedError(),
        LeafDevourerWarfareLeadershipSkill() => throw UnimplementedError(),
        LeptoglossusPhyllopusAmberBarrierSkill() => throw UnimplementedError(),
        LeptoglossusPhyllopusLongAntennaeSkill() => throw UnimplementedError(),
        LeptoglossusPhyllopusVenomousStingSkill() => throw UnimplementedError(),
        LeptomyrmexBurwelliFatalAssaultSkill() => throw UnimplementedError(),
        LeptomyrmexBurwelliAdaptiveAssaultSkill() => throw UnimplementedError(),
        LeptomyrmexBurwelliSweepingStrengthSkill() =>
          throw UnimplementedError(),
        MerannoplusBicolorPlushBackArmorSkill() => throw UnimplementedError(),
        MerannoplusBicolorToxicThornSkill() => throw UnimplementedError(),
        MerannoplusBicolorBufferBarrierSkill() => throw UnimplementedError(),
        MerannoplusCastaneusScarletFurySkill() => throw UnimplementedError(),
        MerannoplusCastaneusBloodyShieldSkill() => throw UnimplementedError(),
        MerannoplusCastaneusHealingWithLoveSkill() =>
          throw UnimplementedError(),
        MimicryMasterMouthPieceAttackSkill() => throw UnimplementedError(),
        MimicryMasterSupressingAttackSkill() => throw UnimplementedError(),
        MimicryMasterSwipeSkill() => throw UnimplementedError(),
        MyrmarachneFormicariaPrettyShellSkill() => throw UnimplementedError(),
        MyrmarachneFormicariaDisguiseStealSkill() => throw UnimplementedError(),
        MyrmarachneFormicariaJumpingImpactSkill() => throw UnimplementedError(),
        MyrmecotypusRettenmeyeriNimblePostureSkill() =>
          throw UnimplementedError(),
        MyrmecotypusRettenmeyeriPowerOfAwakeningSkill() =>
          throw UnimplementedError(),
        MyrmecotypusRettenmeyeriHealthFieldSkill() =>
          throw UnimplementedError(),
        NewWorldGeneralRageBiteSkill() => throw UnimplementedError(),
        NewWorldGeneralDeterenceSkill() => throw UnimplementedError(),
        NewWorldGeneralBlitzkriegSkill() => throw UnimplementedError(),
        NimbleTreeAntAgilitySkill() => throw UnimplementedError(),
        NimbleTreeAntPiercingChaseSkill() => throw UnimplementedError(),
        NimbleTreeAntDeftFootworkSkill() => throw UnimplementedError(),
        PheidoleNietneriBounceBackSkill() => throw UnimplementedError(),
        PheidoleNietneriGladiatorSkillsSkill() => throw UnimplementedError(),
        PheidoleNietneriStrongShellSkill() => throw UnimplementedError(),
        PredatorBloodyBattleSkill() => throw UnimplementedError(),
        PredatorMenaceSkill() => throw UnimplementedError(),
        PredatorFlexibleRobberySkill() => throw UnimplementedError(),
        ProattaKnockbackSkill() => throw UnimplementedError(),
        ProattaDisablingCombosSkill() => throw UnimplementedError(),
        ProattaHorrorHunterSkill() => throw UnimplementedError(),
        ProcryptocerusAdlerziComprehensiveDefenseSkill() =>
          throw UnimplementedError(),
        ProcryptocerusAdlerziSavageChargeSkill() => throw UnimplementedError(),
        ProcryptocerusAdlerziBigBiteSkill() => throw UnimplementedError(),
        ReapMasterBigBiteSkill() => throw UnimplementedError(),
        ReapMasterThrillOfTheHuntSkill() => throw UnimplementedError(),
        ReapMasterGrievousBiteSkill() => throw UnimplementedError(),
        RockBanditRageRushSkill() => throw UnimplementedError(),
        RockBanditHuggerBiteSkill() => throw UnimplementedError(),
        RockBanditWarfareLeadershipSkill() => throw UnimplementedError(),
        RubySlenderRevengeSkill() => throw UnimplementedError(),
        RubySlenderSelfAdjustingSkill() => throw UnimplementedError(),
        RubySlenderWarfareLeadershipSkill() => throw UnimplementedError(),
        SaharanSilverAntRapidMomentumSkill() => throw UnimplementedError(),
        SaharanSilverAntSilverGleamSkill() => throw UnimplementedError(),
        SaharanSilverAntPrecisionLongshotSkill() => throw UnimplementedError(),
        ShieldWardenHealingPowerSkill() => throw UnimplementedError(),
        ShieldWardenFightToDeathSkill() => throw UnimplementedError(),
        ShieldWardenProtectionPostureSkill() => throw UnimplementedError(),
        ShikareeMasterInfiniteDeadhuntSkill() => throw UnimplementedError(),
        ShikareeMasterRampantAttackSkill() => throw UnimplementedError(),
        ShikareeMasterAudaciousChargeSkill() => throw UnimplementedError(),
        SlimArchedBigBiteSkill() => throw UnimplementedError(),
        SlimArchedBlitzkriegSkill() => throw UnimplementedError(),
        SlimArchedSuppressingAttackSkill() => throw UnimplementedError(),
        StrumigenysEggersiStablePostureSkill() => throw UnimplementedError(),
        StrumigenysEggersiDeceptiveFormSkill() => throw UnimplementedError(),
        StrumigenysEggersiKeenIntuitionSkill() => throw UnimplementedError(),
        WeaverAntAcidAssaultSkill() => throw UnimplementedError(),
        WeaverAntFieryThrashSkill() => throw UnimplementedError(),
        WeaverAntTacticalCounterAttackSkill() => throw UnimplementedError(),
        WhiteVelvetMasterOfDisguiseSkill() => throw UnimplementedError(),
        WhiteVelvetHealingPowerSkill() => throw UnimplementedError(),
        WhiteVelvetWhiteGuardianSkill() => throw UnimplementedError(),
        WiseBerserkerCruelStrikeSkill() => throw UnimplementedError(),
        WiseBerserkerContinuousBiteSkill() => throw UnimplementedError(),
        WiseBerserkerBattleMemorySkill() => throw UnimplementedError(),
      };
}
