enum AntId {
  acidGeneral,
  attaSexdens,
  bansheePanda,
  bansheeVelvet,
  blackCancer,
  blackKnight,
  bloodGiant,
  brownRogue,
  bulletAnt,
  carpenterAnt,
  crematogasterInflata,
  crimsonFragger,
  crimsonPearl,
  cyphomyrmexRimosus,
  darkGiant,
  darkHercules,
  dolichoderusBispinosus,
  driverAnt,
  duskyLurker,
  emeraldJewelAnt,
  enigmaticTaylor,
  formicaClara,
  ghostAnt,
  giantTooth,
  goldArmor,
  goldenCrystal,
  goldenSpiny,
  goldenSugar,
  goldenVenom,
  gracefulTwigAnt,
  graveDigger,
  guardGeneral,
  hairyPanther,
  jackJumper,
  jetBlack,
  lathySniffer,
  leafDevourer,
  leptoglossusPhyllopus,
  leptomyrmexBurwelli,
  merannoplusBicolor,
  merannoplusCastaneus,
  mimicryMaster,
  myrmarachneFormicaria,
  myrmecotypusRettenmeyeri,
  newWorldGeneral,
  nimbleTreeAnt,
  pheidoleNietneri,
  predator,
  proatta,
  procryptocerusAdlerzi,
  reapMaster,
  rockBandit,
  rubySlender,
  saharanSilverAnt,
  shieldWarden,
  shikareeMaster,
  slimArched,
  strumigenysEggersi,
  tricondylaAptera,
  weaverAnt,
  whiteVelvet,
  wiseBerserker;

  const AntId();

  String profilePathKey() => switch (this) {
        AntId.acidGeneral => 'acid_general',
        AntId.attaSexdens => 'atta_sexdens',
        AntId.bansheePanda => 'banshee_panda',
        AntId.bansheeVelvet => 'banshee_velvet',
        AntId.blackCancer => 'black_cancer',
        AntId.blackKnight => 'black_knight',
        AntId.bloodGiant => 'blood_giant',
        AntId.brownRogue => 'brown_rogue',
        AntId.bulletAnt => 'bullet_ant',
        AntId.carpenterAnt => 'carpenter_ant',
        AntId.crematogasterInflata => 'crematogaster_inflata',
        AntId.crimsonFragger => 'crimson_fragger',
        AntId.crimsonPearl => 'crimson_pearl',
        AntId.cyphomyrmexRimosus => 'cyphomyrmex_rimosus',
        AntId.darkGiant => 'dark_giant',
        AntId.darkHercules => 'dark_hercules',
        AntId.dolichoderusBispinosus => 'dolichoderus_bispinosus',
        AntId.driverAnt => 'driver_ant',
        AntId.duskyLurker => 'dusky_lurker',
        AntId.emeraldJewelAnt => 'emerald_jewel_ant',
        AntId.enigmaticTaylor => 'enigmatic_taylor',
        AntId.formicaClara => 'formica_clara',
        AntId.ghostAnt => 'ghost_ant',
        AntId.giantTooth => 'giant_tooth',
        AntId.goldArmor => 'gold_armor',
        AntId.goldenCrystal => 'golden_crystal',
        AntId.goldenSpiny => 'golden_spiny',
        AntId.goldenSugar => 'golden_sugar',
        AntId.goldenVenom => 'golden_venom',
        AntId.gracefulTwigAnt => 'graceful_twig_ant',
        AntId.graveDigger => 'grave_digger',
        AntId.guardGeneral => 'guard_general',
        AntId.hairyPanther => 'hairy_panther',
        AntId.jackJumper => 'jack_jumper',
        AntId.jetBlack => 'jet_black',
        AntId.lathySniffer => 'lathy_sniffer',
        AntId.leafDevourer => 'leaf_devourer',
        AntId.leptoglossusPhyllopus => 'leptoglossus_phyllopus',
        AntId.leptomyrmexBurwelli => 'leptomyrmex_burwelli',
        AntId.merannoplusBicolor => 'merannoplus_bicolor',
        AntId.merannoplusCastaneus => 'merannoplus_castaneus',
        AntId.mimicryMaster => 'mimicry_master',
        AntId.myrmarachneFormicaria => 'myrmarachne_formicaria',
        AntId.myrmecotypusRettenmeyeri => 'myrmecotypus_rettenmeyeri',
        AntId.newWorldGeneral => 'new_world_general',
        AntId.nimbleTreeAnt => 'nimble_tree_ant',
        AntId.pheidoleNietneri => 'pheidole_nietneri',
        AntId.predator => 'predator',
        AntId.proatta => 'proatta',
        AntId.procryptocerusAdlerzi => 'procryptocerus_adlerzi',
        AntId.reapMaster => 'reap_master',
        AntId.rockBandit => 'rock_bandit',
        AntId.rubySlender => 'ruby_slender',
        AntId.saharanSilverAnt => 'saharan_silver_ant',
        AntId.shieldWarden => 'shield_warden',
        AntId.shikareeMaster => 'shikaree_master',
        AntId.slimArched => 'slim_arched',
        AntId.strumigenysEggersi => 'strumigenys_eggersi',
        AntId.tricondylaAptera => 'tricondyla_aptera',
        AntId.weaverAnt => 'weaver_ant',
        AntId.whiteVelvet => 'white_velvet',
        AntId.wiseBerserker => 'wise_berserker',
      };
}
