enum ScientificSpecies {
  mystriumOberthueri, // 'Mystrium oberthueri'
  attaSexdens, // Atta Sexdens
  euspinoliaMilitaris, // Euspinolia militaris
  dasymutillaOccidentalis, // Dasymutilla occidentalis
  aphantochilusRogersi, // Aphantochilus rogersi
  cephalotesAlfaroi, // Cephalotes alfaroi
  nomamyrmexEsenbeckii, // Nomamyrmex esenbeckii
  myrmarachnePlataleoides, // Myrmarachne plataleoides
  paraponeraClavata, // Paraponera clavata
  camponotusColoratus, // Camponotus coloratus
  crematogasterInflata, // Crematogaster inflata
  camponotusChromaiodes, //Camponotus chromaiodes
  myrmarachneSp, // Myrmarachne sp
  cyphomyrmexRimosus, // Cyphomyrmex rimosus
  ecitonRapax, // Eciton rapax
  myrmarachneGisti, // Myrmarachne Gisti
  dolichoderusBispinosus, // Dolichoderus bispinosus
  dorylusDriver, // Dorylus driver
  ampulexCompressa, // Ampulex compressa
  tetramoriumPulcherrimum, // Tetramorium pulcherrimum
  formicaClara, // Formica Clara
  tapinomaMelanocephalum, // Tapinoma melanocephalum
  odontomachusCoquereli, // Odontomachus coquereli
  dacetonArmigerum, // Daceton armigerum
  leptogenysElongata, // Leptogenys elongata
  polyrhachisTrapezoidea, // Polyrhachis trapezoidea
  camponotusSericeiventris, // Camponotus sericeiventris
  telamoniaDimidiata, // Telamonia dimidiata,
  pseudomyrmexGracilis, // Pseudomyrmex gracilis
  prionopeltaHumicola, // Prionopelta humicola
  harpegnathosVenator, // Harpegnathos venator
  neoponeraVillosa, // Neoponera villosa
  myrmeciaPilosula, // Myrmecia pilosula
  plectroctenaCristata, // Plectroctena cristata
  tetraponeraRufonigra, // Tetraponera
  attaLaevigata, // Atta laevigata
  leptoglossusPhyllopus, // Leptoglossus Phyllopus
  leptomyrmexBurwelli, // Leptomyrmex Burwelli
  merannoplusBicolor, // Merannoplus bicolor
  merannoplusCastaneus, // Merannoplus castaneus
  myrmarachneFormicaria, // Myrmarachne Formicaria
  myrmecotypusRettenmeyeri, // Myrmecotypus Rettenmeyeri
  echitonBurchellii, // Echiton burchellii
  pseudomyrmexBoopis, // Pseudomyrmex boopis
  pheidoleNietneri, // Pheidole nietneri
  psalidomyrmexReichenspergeri, // Psalidomyrmex reichenspergeri
  proattaButteli, // Proatta butteli
  procryptocerusAdlerzi, // Procryptocerus Adlerzi
  thaumatomyrmexAtrox, // Thaumatomyrmex Atrox
  cyphomyrmexFlavidus, // Cyphomyrmex flavidus
  gnamptogenysMordax, // Gnamptogenys mordax
  cataglyphisBombycina, // Cataglyphis bombycina
  cataulacusHuberi, // Cataulacus huberi
  arilusCristatus, // Arilus cristatus
  camponotusMirabilis, // Camponotus mirabilis
  strumigenysEggersi, // Strumigenys Eggersi
  oecophyllaLonginoda, // Oecophylla longinoda
  dasymutillaGloriosa, // Dasymutilla gloriosa
  mystriumCamillae, // Mystrium camillae
}
